version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  kittygram_db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: i0ne1y/kittygram_backend:latest
    env_file: .env
    volumes:
      - static_volume:/static/
      - media_volume:/app/media/
    depends_on:
      - kittygram_db
  frontend:
    image: i0ne1y/kittygram_frontend:latest
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static_volume:/static
  gateway:
    image: i0ne1y/kittygram_gateway:latest
    env_file: .env
    volumes:
      - static_volume:/static
      - media_volume:/media
    ports:
      - 9000:80
    depends_on:
      - frontend
      - backend
